### ISSUE TITLE
Importing the example catalogue [supernovae] results in error RuntimeError: Return value should have been None!

### ISSUE THREAD

**Issue by lib-j** [astrocatalogs/astrocats#90]
Trying to work through the examples to creat my own catalogue be when running the command python -m astrocats catalog import as listed in 1.2 of https://github.com/astrocatalogs/astrocats/wiki/Catalog-Creation-Guide
I get this error.

Please advise on how to fix.

Astrocats, version: 0.3.29, SHA: b'v0.2-479-g8af62c454'
=======================================================
Thu Dec 14 21:05:47 2017

```
 - - Running 'import'.
 - - - Deleting all old entry files.
<2017-12-14 21:05:48> Deleting old entries: 0it [00:00, ?it/s]
 - - - Task: 'test'
/Users/ojones/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
 - - - - - - Warning: cached file '/Users/ojones/Python/astrocats/astrocats/catalog/input/catalog-test-input/google-test-1.txt' does not exist. And is not being saved.
/Users/ojones/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
 - - - - - - Warning: cached file '/Users/ojones/Python/astrocats/astrocats/catalog/input/catalog-test-input/google-test-1.txt' does not exist. And is not being saved.
 - - - - - - Return value should have been None!
'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html><head><meta http-equiv="refresh" content="0;url=http://www.webaddresshelp.bt.com/main?ParticipantID=mg76cjr54t8kx45jjw4j4k9j5hsr5m26&FailedURI=http%3A%2F%2Fwww.badgoobadglebad.com%2F&FailureMode=1&Implementation=&AddInType=4&Version=pywr1.0&ClientLocation=uk"/><script type="text/javascript">url="http://www.webaddresshelp.bt.com/main?ParticipantID=mg76cjr54t8kx45jjw4j4k9j5hsr5m26&FailedURI=http%3A%2F%2Fwww.badgoobadglebad.com%2F&FailureMode=1&Implementation=&AddInType=4&Version=pywr1.0&ClientLocation=uk";if(top.location!=location){var w=window,d=document,e=d.documentElement,b=d.body,x=w.innerWidth||e.clientWidth||b.clientWidth,y=w.innerHeight||e.clientHeight||b.clientHeight;url+="&w="+x+"&h="+y;}window.location.replace(url);</script></head><body></body></html>'
Traceback (most recent call last):
  File "/Users/ojones/Python/astrocats/astrocats/main.py", line 306, in <module>
    main()
  File "/Users/ojones/Python/astrocats/astrocats/main.py", line 68, in main
    mod.main.main(args, sub_clargs, log)
  File "/Users/ojones/Python/astrocats/astrocats/catalog/main.py", line 25, in main
    args_handler.run_subcommand(args, catalog)
  File "/Users/ojones/Python/astrocats/astrocats/catalog/argshandler.py", line 22, in run_subcommand
    catalog.import_data()
  File "/Users/ojones/Python/astrocats/astrocats/catalog/catalog.py", line 271, in import_data
    getattr(mod, func_name)(self)
  File "/Users/ojones/Python/astrocats/astrocats/catalog/tasks/test.py", line 44, in do_test
    test_load_url(catalog)
  File "/Users/ojones/Python/astrocats/astrocats/catalog/tasks/test.py", line 433, in test_load_url
    log_raise(err_str, log)
  File "/Users/ojones/Python/astrocats/astrocats/catalog/tasks/test.py", line 460, in log_raise
    raise RuntimeError(err_str)
RuntimeError: Return value should have been None!
'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html><head><meta http-equiv="refresh" content="0;url=http://www.webaddresshelp.bt.com/main?ParticipantID=mg76cjr54t8kx45jjw4j4k9j5hsr5m26&FailedURI=http%3A%2F%2Fwww.badgoobadglebad.com%2F&FailureMode=1&Implementation=&AddInType=4&Version=pywr1.0&ClientLocation=uk"/><script type="text/javascript">url="http://www.webaddresshelp.bt.com/main?ParticipantID=mg76cjr54t8kx45jjw4j4k9j5hsr5m26&FailedURI=http%3A%2F%2Fwww.badgoobadglebad.com%2F&FailureMode=1&Implementation=&AddInType=4&Version=pywr1.0&ClientLocation=uk";if(top.location!=location){var w=window,d=document,e=d.documentElement,b=d.body,x=w.innerWidth||e.clientWidth||b.clientWidth,y=w.innerHeight||e.clientHeight||b.clientHeight;url+="&w="+x+"&h="+y;}window.location.replace(url);</script></head><body></body></html>'

Process finished with exit code 1
```

**Comment by guillochon** [comment]
CC @lzkelley

**Comment by harej10** [comment]
I am running into this same issue and was wondering if it was ever resolved?

Thanks!
